singer = "Rie Takahashi"
print(len(singer))
print(singer.upper())
print(singer.lower())
print(singer.find('s'))
print(singer.find('b'))
print(singer.find('shi'))
print(singer.replace('i', 'e'))
print('Rie' in singer)
print('rie' in singer)
