singer = "Rie Takahashi"
print(len(singer))
print(singer.upper())
print(singer.lower())
print(singer.find('s'))
print(singer.find('b'))
print(singer.find('shi'))
print(singer.replace('i', 'e'))
print('Rie' in singer)
print('rie' in singer)
print(singer[::-1])
print(singer.swapcase())
word = singer.split(" ")
new_singer = " ".join(reversed(word))
print(new_singer)
